CREATE USER Quan IDENTIFIED BY 123;
GRANT CREATE SESSION TO Quan;
GRANT CREATE TABLE TO Quan;

ALTER USER Quan QUOTA 100M ON users;

CREATE TABLE LOP (
    MALOP VARCHAR2(10) PRIMARY KEY,
    TENLOP VARCHAR2(30),
    SISO NUMBER(3)
);

CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(30),
    NGAHSINH DATE,
    MALOP VARCHAR2(10),
    CONSTRAINT FK_SV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);


INSERT INTO LOP (MALOP, TENLOP, SISO) VALUES ('13DHTH1', '13 Đại học Tin học 1', 50);
INSERT INTO LOP (MALOP, TENLOP, SISO) VALUES ('13DHTH2', '13 Đại học Tin học 2', 40);
INSERT INTO LOP (MALOP, TENLOP, SISO) VALUES ('13DHBM1', '13 Đại học Bảo mật 1', 55);

INSERT INTO SINHVIEN (MASV, HOTEN, NGAHSINH, MALOP) VALUES ('SV001', 'Trần Lệ Quyên', TO_DATE('21-01-2004', 'DD-MM-YYYY'), '13DHTH1');
INSERT INTO SINHVIEN (MASV, HOTEN, NGAHSINH, MALOP) VALUES ('SV003', 'Tô Ánh Nguyệt', TO_DATE('02-05-2004', 'DD-MM-YYYY'), '13DHBM1');

-- a
SELECT TENLOP, SISO FROM LOP;

-- b
SELECT MASV, HOTEN 
FROM LOP, SINHVIEN
WHERE LOP.MALOP = SINHVIEN.MALOP AND TENLOP = '13 Đại học Tin học 1';

-- c
SELECT MALOP, TENLOP, SISO
FROM LOP
ORDER BY SISO ASC;

-- d
SELECT MASV, HOTEN, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM NGAHSINH) AS TUOI
FROM SINHVIEN;

-- e
SELECT LOP.MALOP, LOP.TENLOP, COUNT(SINHVIEN.MASV) AS SOLUONG
FROM LOP
LEFT JOIN SINHVIEN ON LOP.MALOP = SINHVIEN.MALOP
GROUP BY LOP.MALOP, LOP.TENLOP;