CREATE TABLE GIAOVIEN
(
    MAGV VARCHAR(10) PRIMARY KEY,
    TENGV NVARCHAR2(50),
    NGAYSINH DATE,
    GIOITINH    NVARCHAR2(10),
    DIENTHOAI VARCHAR2(11),
    MAGVQUANLI VARCHAR2(7)
    
)
ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_GV FOREIGN KEY ( MAGVQUANLI) REFERENCES GIAOVIEN(MAGV);



CREATE TABLE LOPHOC
(
    MALOP VARCHAR(10) PRIMARY KEY,
    SISO INT,
    LOPTRUONG VARCHAR2(8),
    MAGVQUANLI VARCHAR(10),
    NAMBATDAU NUMBER,
    NAMKETTHUC NUMBER,
    CONSTRAINT FK_LOPHOC FOREIGN KEY (MAGVQUANLI) REFERENCES GIAOVIEN(MAGV)

)


CREATE TABLE HOCVIEN
(
    MAHOCVIEN VARCHAR2(8) PRIMARY KEY,
    TENHOCVIEN NVARCHAR2(50),
    NGAYSINH DATE,
    TINHTRANG NVARCHAR2(50),
    MALOP VARCHAR(10),
    CONSTRAINT FK_LOPHOC_HOCVIEN FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)
)



CREATE TABLE MONHOC
(
    MAMONHOC VARCHAR(10) PRIMARY KEY,
    TENMONHOC NVARCHAR2(50), 
    SOCHI NUMBER
)

CREATE TABLE PHANCONG
(
    MAGV VARCHAR(10) NOT NULL,
    MAMH VARCHAR(10) NOT NULL,
    MALOP VARCHAR(10) NOT NULL,
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MAGV, MAMH, MALOP),
    CONSTRAINT FK_PHANCONG_PC1  FOREIGN KEY (MAGV, MAMH) REFERENCES GIAOVIEN_DAY_MONHOC(MAGV,MAMH),
    CONSTRAINT FK_PHANCONG_Pc2  FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)

)


CREATE TABLE GIAOVIEN_DAY_MONHOC
(
    MAGV VARCHAR(10),
    MAMH VARCHAR(10),
    THAMNIEN NUMBER,
    SOLOPDADAY NUMBER,
    CONSTRAINT PK_MONHOC_GIAOVIEN_DAY_MONHOC PRIMARY KEY (MAGV, MAMH),
    CONSTRAINT FK_MONHOC_Gv_DAY_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMONHOC),
    CONSTRAINT FK_GIAOVIEN_Gv_DAY_MONHOC FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

)

CREATE TABLE KETQUA 
(
    MAHOCVIEN VARCHAR2(8),
    MAMONHOC VARCHAR(10),
    LANTHI NUMBER,
    DIEM FLOAT,
    CONSTRAINT PK_KETQUA PRIMARY KEY (MAHOCVIEN, MAMONHOC, LANTHI),
    CONSTRAINT FK_HOCVIEN FOREIGN KEY (MAHOCVIEN) REFERENCES HOCVIEN(MAHOCVIEN),
    CONSTRAINT FK_MONHOC FOREIGN KEY (MAMONHOC) REFERENCES MONHOC(MAMONHOC)
)
ALTER TABLE LOPHOC
ADD CONSTRAINT FK_LOPTRUONG FOREIGN KEY (LOPTRUONG) REFERENCES HOCVIEN(MAHOCVIEN);


DROP TABLE LOPHOC;
DROP TABLE GIAOVIEN_DAY_MONHOC;
DROP TABLE KETQUA;
DROP TABLE PHANCONG;
DROP TABLE MONHOC;
DROP TABLE HOCVIEN;
DROP TABLE GIAOVIEN;

